### ISSUE TITLE
Getting "Error: Bad Request" when I try to start a dishwasher program

### ISSUE THREAD

**Issue by emeins** [alexkn/node-red-contrib-homeconnect#10]
I am running node-red-contrib-homeconnect in a docker container Node Red instance. The home connect is implemented & authorized as described and I am able to run all the get requests with successfully. Unfortunately the set requests do not work. So I am not able to start a dishwasher program (remote start on the device is enabled) or set any option value for a program.

![image](https://user-images.githubusercontent.com/17033201/85586331-2221ee80-b641-11ea-8314-77cbe9885edb.png)

Any idea?

**Comment by alexkn** [comment]
The body must be a JSON object.
See examples in
https://developer.home-connect.com/docs/dishwasher/supported_programs_options

**Comment by emeins** [comment]
Perfect, thx @alexkn. I changed it to a JSON structure and it is working fine. Maybe a hint in the documentation would help also the other users.
![image](https://user-images.githubusercontent.com/17033201/85690101-85f4f780-b6d3-11ea-9282-9784412c0d1f.png)
