### ISSUE TITLE
Wrong protocol for callback URL when using Node-RED behind a reverse proxy

### ISSUE THREAD

**Issue by hobbyquaker** [alexkn/node-red-contrib-homeconnect#11]
Hi!

My Node-RED instance is running behind a reverse proxy that offers https. The callback_url doesnt respect that cause the request from the proxy to node-red is plain http and so `req.protocol` is `http://` then.

So I'm accessing Node-RED via e.g. `https://node-red` but the callback_url then points the oauth flow back to `http://node-red`.

I can offer to create a PR, would you accept that? 

Possible Solutions that came to my mind:

* Make the `callback_url` configurable
* Look for a `X-Forwarded-*` header (that then has to be set by the reverse proxy)
* Hand through `window.location` to the `/homeconnect/auth/start` endpoint
* Use the `Referer` header

I would prefer the possibility to make the callback_url configurable. Simple, but bullet proof. If left empty it would still default to the current `req.protocol + '://' + req.get('host') + '/homeconnect/auth/callback` - so nothing should break.

What do you think?

Regards,
Sebastian

**Comment by alexkn** [comment]
I think configurable in the auth node properties would be great.
And preset with window.location + /homeconnect/auth/callback, so you can copy it to the developer portal.

Feel free to send a pull request.

**Comment by hobbyquaker** [comment]
https://github.com/alexkn/node-red-contrib-homeconnect/pull/12

**Comment by alexkn** [comment]
resolved with #12
