### ISSUE TITLE
please make a sample flow

### ISSUE THREAD

**Issue by koburg** [alexkn/node-red-contrib-homeconnect#13]
Hi can you please make a sample flow I can not get I fully to work. the call back is not working and I get ok when using the call back local. but I try authentificaton both on simulation and with real devices:

{
  "error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized"
}

so if you made a sample flow maybe many beginner errors would be eliminated.

thanks

**Comment by alexkn** [comment]
I think it is not a problem with the Node-RED flow but incorrectly configured in the HomeConnect Developer Portal.

**Comment by alexkn** [comment]
callback should respond with error message now
