### ISSUE TITLE
Event Stream no longer works if internet connection is lost and reconnected

### ISSUE THREAD

**Issue by mathiaslehmann** [alexkn/node-red-contrib-homeconnect#14]
Hello,
I have the problem that the event stream no longer works when the internet connection is interrupted, e.g. during the forced separation at night. A new deploy or restart of Node Red fixes the problem. Is there a trick here to work around the problem.

Thank you.

**Comment by alexkn** [comment]
I haven't seen such problems yet.
But my internet connection stays active for weeks.
Usually the eventsource component should reconnect automatically.

**Comment by mathiaslehmann** [comment]
Hello, unfortunately it is the case with us that the Internet connection is forcibly cut off every night by the provider 1 & 1. I tested a lot again. If the internet connection is disconnected and reconnected, the "home connect request" block works fine, but the "home connect event" block no longer gives me any events from the device. All blocks each indicate a ready. The problem is only solved by restarting Node Red or deploying in Node Red without changing anything. I suspect that this will re-establish the connection. One solution would be to restart Node Red every night after the forced disconnection. Can you maybe implement a reconnection function that I can trigger as a user? Thanks for the efforts.

**Comment by alexkn** [comment]
I can reproduce the problem.
I never noticed, probably because my connection rarely disconnects and the event node at lease reconnects after 24 hours when the access token expires.

HomeConnect is also sending KEEP-ALIVE events every minute.
I think I can use them to trigger a reconnect.
