### ISSUE TITLE
Scope Error

### ISSUE THREAD

**Issue by pannlala** [alexkn/node-red-contrib-homeconnect#17]
I am getting this error
{"error":"invalid_scope","error_description":"given scope doesn't match requested scope"}
when I try to authorize Oven, Control or Oven-Control. Same with Hob. Washer, Hood etc works fine.

**Comment by alexkn** [comment]
https://developer.home-connect.com/docs/authorization/scope
see "Additional Partner Agreement required"

**Comment by leifnel** [comment]
There are dead links describing this. How can I get this agreement as a non-business?

**Comment by leifnel** [comment]
Oven controll is not available for us mere mortals yet. See this discussion. https://github.com/alexkn/node-red-contrib-homeconnect/discussions/35

It should be available around summer 2021.
