### ISSUE TITLE
Red Event after Deploy

### ISSUE THREAD

**Issue by mathiaslehmann** [alexkn/node-red-contrib-homeconnect#18]
Hello, I currently get an event from node red every time I deploy.

"[RED.events] Deprecated use of "nodes-started" event from "/home/pi/.node-red/node_modules/node-red-contrib-homeconnect/nodes/home-connect-auth.js:73:20". Use "flows:started" instead."

I suspect a component is out of date. Can this be? 
Node Red is version 1.2.1.

Thank you for the effort.

**Comment by alexkn** [comment]
Yes, the event is deprecated since 1.2.0
I haven't updated yet.
But it should still work.

Thanks for your information, I'll fix that soon.
