### ISSUE TITLE
How to catch "get_active_program" errors?

### ISSUE THREAD

**Issue by HomeMatic-INSIDE** [alexkn/node-red-contrib-homeconnect#38]
Hi,

I'm using the "home_connect_request" node to "get_active_program" from the given HAID and this works as expected - but: as soon as there's no active program available, the node throws an error which will be displayed in the debug window:

```
msg : string[67]
"404 Not Found SDK.Error.NoProgramActive: There is no program active"
```

I wan't to capture this error using the "catch"-node, but this doesn't work - the node is never triggered by the error.

Any idea why this doesn't work?

Thank you,...

**Comment by alexkn** [comment]
Looks like it's not correctly implemented to report the error to the runtime.
What do you want to do exactly with the catched error?

**Comment by alexkn** [comment]
catch should work with [v0.6.3](https://github.com/alexkn/node-red-contrib-homeconnect/releases/tag/v0.6.3)

**Comment by HomeMatic-INSIDE** [comment]
Hi - thanks for fixing. I wonna use this to reset a progress bar if the active program has been stopped...or the disher was powered off.
