### ISSUE TITLE
Error with haid

### ISSUE THREAD

**Issue by euDominic** [alexkn/node-red-contrib-homeconnect#46]
"Error: Required parameter haId is not provided"

After 3 Months i geht this error in the debug window of nodeRed:
"Error: Required parameter haId is not provided"

No changes on the machine or the nodes.
![Unbenannt](https://user-images.githubusercontent.com/88461637/128257970-35a2eb4c-21df-4aca-81f3-ea3315020ad0.jpg)

**Comment by osvedman** [comment]
I started having this problem out of the blue yesterday as well. No changes to my flows or node-red.
Tried restarting node-red, recreating the flow nodes from scratch, etc. No cigar.

**Comment by xerion3800** [comment]
I can confirm the same behaiviour in my envoirement. No chnages but i got as well the same error message.

**Comment by alexkn** [comment]
Looks line Home Connect renamed the haid parameter to haId. (upper case i)
should be fixed in [v0.6.4](https://github.com/alexkn/node-red-contrib-homeconnect/releases/tag/v0.6.4)

**Comment by xerion3800** [comment]
After the Update to v0.6.4 i got now this error:

7 Aug 08:33:19 - [info] Waiting for missing types to be registered:
7 Aug 08:33:19 - [info]  - home-connect-request

**Comment by alexkn** [comment]
> After the Update to v0.6.4 i got now this error:
> 
> 7 Aug 08:33:19 - [info] Waiting for missing types to be registered:
> 7 Aug 08:33:19 - [info] - home-connect-request

Check the logs.
I guess you need to update your nodejs.

**Comment by xerion3800** [comment]
Thank you... yes an update was the solution.
