### ISSUE TITLE
home-connect-request

### ISSUE THREAD

**Issue by Dabbadoeber** [alexkn/node-red-contrib-homeconnect#48]
I can not implement the "home-connect-request"  Node
i get an error with, an exclemation mark with [object,object].

Any ideas (Node-red V1.3.6)

![image](https://user-images.githubusercontent.com/9031962/130431464-bf303a1d-69bb-47bb-af55-505e2e0c2246.png)

**Comment by alexkn** [comment]
Try to update your nodejs.

**Comment by Dabbadoeber** [comment]
Ok, hmmm
i am running node-red in a docker image on my synology NAS.
Do you know how to update this nodejs, form inside the docker image ?

**Comment by alexkn** [comment]
You can not update nodejs inside a docker container.
You have to use an newer node-red docker image.

**Comment by Dabbadoeber** [comment]
Thx done, i installed a new container. and everything is up and running.
now trying to get the aplliances back, into node-red
