### ISSUE TITLE
How to authorise for multiple scopes

### ISSUE THREAD

**Issue by nhe050** [alexkn/node-red-contrib-homeconnect#5]
Great work you're doing on this node-red contrib project!
I'm trying to find my way around the possibilities. HomeConnect's API documentation is pretty good, so that'll work.
One thing though, how can I authorise for multiple scopes?
API Doc says to provide multiple scopes separated by %20 (space). However, whatever I try, I can't seem to get the auth node to produce a valid request with multiple scopes.
How should it be done?

**Comment by alexkn** [comment]
On my system it works with spaces.
Escaping to %20 is done automatically.

Maybe there are invalid combinations of scopes?

**Comment by nhe050** [comment]
Thanks for your response. I tried a couple of different ways and managed to get it working now. Turns out I had to fill in the scopes separated by spaces, hit update, then reopen the auth node and start authorisation. Finally hit update again.
Without the intermediate "update" action I kept getting request errors.

**Comment by alexkn** [comment]
I cannot reproduce the problem.
Which error messages do you see?

**Comment by nhe050** [comment]
I tried reproducing it tonight, but seems like I can't. If I add a non-existing scope I'm getting the same error message that does not say much though. 
`
requestToken failed: {
  "error": "invalid_request",
  "error_description": "missing or invalid request parameters"
}`

I got this message before with the config I currently have where scope is 
``IdentifyAppliance Monitor``

**Comment by electron23** [comment]
Same here with scope "Oven-Control"
