### ISSUE TITLE
home-connect-event node periodically gives: {"type":"error"}

### ISSUE THREAD

**Issue by DOSprojects** [alexkn/node-red-contrib-homeconnect#56]
Hello

Every now and then (probably every hour). the event node gives an error. The logfile only prints:

26 Feb 17:23:27 - [error] [home-connect-event:vaatwas] {"type":"error"}

I only monitor a dishwasher. I don't think there were actions on that dishwasher at these moments.

Thanks in advance

**Comment by alexkn** [comment]
I also see this in my logs about once a day.
I think that are just connection losses from the event stream.
Do you have any issues with your network connection?
