### ISSUE TITLE
Error: Forbidden

### ISSUE THREAD

**Issue by joepv** [alexkn/node-red-contrib-homeconnect#7]
Everything I do, I get a `Error: Forbidden` message back.

I set up a developer account and an application with `Authorization Code Grant Flow`.

The redirect uri is my Node-RED test machine: `http://192.168.2.2:1880/homeconnect/auth/callback`
(this machine is not accessible from the Internet).

I get a login prompt when authorizing with the `oauth` settings dialog. I log in with my Home Connect credentials used to connect the iOS app and see dishwasher with all authorizations and press `Authorize` button.

The Redirect URL gives an `OK` in the browser and the `oauth` settings dialog give's a `tokens received' message. I **update**, and **deploy**. The request node gives a **green** **dot** with **ready**.

Settings in request node:
* tag: `General`
* action: `get_home_appliances`

Scope in _oauth_ dialog: `Dishwasher`.

I double checked my `Client ID` and `Client Secret`.

I do not have an blue oauth node, only a `request` and `event` node. oauth is in the request node as config button.

Can you please help me? I do not get what I'm doing wrong.

**Comment by alexkn** [comment]
Try to add IdentifyAppliance to scope.

**Comment by joepv** [comment]
This works. You are a legend. 🙏🏻
