### ISSUE TITLE
Refresh Token and Authorization not working anymore

### ISSUE THREAD

**Issue by joepv** [alexkn/node-red-contrib-homeconnect#9]
Since yesterday the token cannot be refreshed and I tried to set up a new authorisation and this doesn't function. The callback URL says `ok` and the `auth-node` keeps daying `authorizing`.

Node-RED gives this error:

```
node-red   | 1 Jun 19:56:35 - SyntaxError: Unexpected token u in JSON at position 0
node-red   |     at JSON.parse (<anonymous>)
node-red   |     at parseToken (/data/node_modules/node-red-contrib-homeconnect/lib/ApiService.js:27:23)
node-red   |     at Request.request.post [as _callback] (/data/node_modules/node-red-contrib-homeconnect/lib/ApiService.js:104:25)
node-red   |     at self.callback (/data/node_modules/node-red-contrib-homeconnect/node_modules/request/request.js:185:22)
node-red   |     at emitOne (events.js:116:13)
node-red   |     at Request.emit (events.js:211:7)
node-red   |     at Request.onRequestError (/data/node_modules/node-red-contrib-homeconnect/node_modules/request/request.js:877:8)
node-red   |     at emitOne (events.js:116:13)
node-red   |     at ClientRequest.emit (events.js:211:7)
node-red   |     at TLSSocket.socketErrorListener (_http_client.js:401:9)
node-red   | npm ERR! code ELIFECYCLE
node-red   | npm ERR! errno 1
```

It worked for 2 a 3 weeks withouth problems. Is this a known issue.

**Comment by alexkn** [comment]
It looks like the home connect cloud is not responding correctly.

https://developer.home-connect.com/simulator 
also responds with an error.

**Comment by joepv** [comment]
I have another test Node-RED machine which was offline during 1 week and there it works. The token is immediately refreshed. This confuses me, because nothing has changed on my "production" Node-RED as making a new flow with a http node and a simple function.

Is there more logging available for the `home-connect-auth` node?

**Comment by joepv** [comment]
I removed the flows and uninstalled the `home-connect` modules and after a new install it's still the same. Also simulation is not working anymore. I did some research yesterday and it looks like the Bosch auth website does a `302` redirection, does it fail on that maybe?

**Comment by alexkn** [comment]
I don't see any problems.
