### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'get_status_value')

### ISSUE THREAD

**Issue by etofi** [alexkn/node-red-contrib-homeconnect#90]
Ich bekomme gerade für jeden Abfrage die ich mache die Fehlermeldung obwohl die Verbindung mit "ready" bestätigt ist.

`
TypeError: Cannot read properties of undefined (reading 'get_status_value')`

Also letzte Woche hat das noch funktioniert und seither habe ich ich nichts geändert.

![grafik](https://github.com/alexkn/node-red-contrib-homeconnect/assets/19774831/c3a8b7e9-4800-4b30-818f-0d2753ae1302)

**Comment by osvedman** [comment]
I started having this problem a couple of days ago as well. Still happening and I have not changed anything either.

**Comment by kevin14389** [comment]
I also have a problem for a few days. I don't know why but I can't connect with auth. He is still "connecting...". I changed nothing !! Is this a change from Siemens ?

**Comment by thomasjetzinger** [comment]
Same problem here

**Comment by imbence** [comment]
I just installed the node, auth seems to be working but having a similar error when trying to get appliances.

`TypeError: Cannot read properties of undefined (reading 'get_home_appliances')`

**Comment by blaxer** [comment]
Same here:

TypeError: Cannot read properties of undefined (reading 'get_status')

**Comment by alexkn** [comment]
Tags are renamed in homeconnect api:
default -> appliances
status_events -> status

Should be fixed in [v0.6.7](https://github.com/alexkn/node-red-contrib-homeconnect/releases/tag/v0.6.7)

**You have to reconfigure your nodes to use the new tags!**
